# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Test Client

on:
  push:
    branches: [ "main" ] # Trigger the workflow on code pushes
  pull_request:
    branches: [ "main" ] # Trigger the workflow on pull request

jobs:
  test:
    runs-on: windows-latest  # Use the latest version of Windows as the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your repository's code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Specify the Python version you want to use


      - name: Run unit tests
        run: python -m unittest unit_test_client.py  # Replace with the correct path to your test file
