# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Test Client

on:
  push:
    branches: [ "main" ] # Trigger the workflow on code pushes
  pull_request:
    branches: [ "main" ] # Trigger the workflow on pull request

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          #pip install -r requirements.txt  # Install your project's dependencies
          pip install cryptography        # Install the 'cryptography' module

      - name: Run unit tests
        run: python -m unittest unit_test_client.py
